// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomeDocumentDataSlicesSlice =
  | CustomToggleSlice
  | SocialIconsSlice
  | CtaListSlice
  | ProfileAvatarSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

export type AllDocumentTypes = HomeDocument;

/**
 * Primary content in *CtaList → Default → Primary*
 */
export interface CtaListSliceDefaultPrimary {
  /**
   * CTAs field in *CtaList → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_list.default.primary.ctas
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  ctas: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Default variation for CtaList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Displays a list of CTA buttons with customizable text and links.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CtaList*
 */
type CtaListSliceVariation = CtaListSliceDefault;

/**
 * CtaList Shared Slice
 *
 * - **API ID**: `cta_list`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaListSlice = prismic.SharedSlice<
  "cta_list",
  CtaListSliceVariation
>;

/**
 * Primary content in *CustomToggle → Default → Primary*
 */
export interface CustomToggleSliceDefaultPrimary {
  /**
   * show_theme_toggle field in *CustomToggle → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: custom_toggle.default.primary.show_theme_toggle
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_theme_toggle: prismic.BooleanField;
}

/**
 * Default variation for CustomToggle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CustomToggleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CustomToggleSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CustomToggle*
 */
type CustomToggleSliceVariation = CustomToggleSliceDefault;

/**
 * CustomToggle Shared Slice
 *
 * - **API ID**: `custom_toggle`
 * - **Description**: CustomToggle
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CustomToggleSlice = prismic.SharedSlice<
  "custom_toggle",
  CustomToggleSliceVariation
>;

/**
 * Primary content in *ProfileAvatar → Default → Primary*
 */
export interface ProfileAvatarSliceDefaultPrimary {
  /**
   * Avatar Image field in *ProfileAvatar → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: profile_avatar.default.primary.avatar_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  avatar_image: prismic.ImageField<never>;

  /**
   * Username or Handle field in *ProfileAvatar → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: profile_avatar.default.primary.username
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  username: prismic.KeyTextField;
}

/**
 * Default variation for ProfileAvatar Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard profile avatar with username below the image.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProfileAvatarSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProfileAvatarSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ProfileAvatar*
 */
type ProfileAvatarSliceVariation = ProfileAvatarSliceDefault;

/**
 * ProfileAvatar Shared Slice
 *
 * - **API ID**: `profile_avatar`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProfileAvatarSlice = prismic.SharedSlice<
  "profile_avatar",
  ProfileAvatarSliceVariation
>;

/**
 * Item in *SocialLinks → Default → Primary → social link*
 */
export interface SocialIconsSliceDefaultPrimarySocialLinkItem {
  /**
   * icon field in *SocialLinks → Default → Primary → social link*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: social_icons.default.primary.social_link[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * link field in *SocialLinks → Default → Primary → social link*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Linkedin
   * - **API ID Path**: social_icons.default.primary.social_link[].social_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  social_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *SocialLinks → Default → Primary*
 */
export interface SocialIconsSliceDefaultPrimary {
  /**
   * social link field in *SocialLinks → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: social_icons.default.primary.social_link[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_link: prismic.GroupField<
    Simplify<SocialIconsSliceDefaultPrimarySocialLinkItem>
  >;
}

/**
 * Default variation for SocialLinks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Displays a horizontal list of social media icon links.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SocialIconsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SocialIconsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SocialLinks*
 */
type SocialIconsSliceVariation = SocialIconsSliceDefault;

/**
 * SocialLinks Shared Slice
 *
 * - **API ID**: `social_icons`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SocialIconsSlice = prismic.SharedSlice<
  "social_icons",
  SocialIconsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      AllDocumentTypes,
      CtaListSlice,
      CtaListSliceDefaultPrimary,
      CtaListSliceVariation,
      CtaListSliceDefault,
      CustomToggleSlice,
      CustomToggleSliceDefaultPrimary,
      CustomToggleSliceVariation,
      CustomToggleSliceDefault,
      ProfileAvatarSlice,
      ProfileAvatarSliceDefaultPrimary,
      ProfileAvatarSliceVariation,
      ProfileAvatarSliceDefault,
      SocialIconsSlice,
      SocialIconsSliceDefaultPrimarySocialLinkItem,
      SocialIconsSliceDefaultPrimary,
      SocialIconsSliceVariation,
      SocialIconsSliceDefault,
    };
  }
}
