import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="w-full min-h-screen py-14 bg-[url('/assets/images/bg-mobile-light.webp')] md:bg-[url('/assets/images/bg-desktop-light.webp')] dark:bg-[url('/assets/images/bg-mobile.webp')] md:dark:bg-[url('/assets/images/bg-desktop.webp')] bg-cover bg-center">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
